version: "3.9"

services:
  db:
      image: postgres:14
      container_name: odoo-db
      restart: always
      environment:
        POSTGRES_USER: odoo
        POSTGRES_PASSWORD: odoo
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U odoo"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        - odoo-net
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST=luminostudio.ca
      - LETSENCRYPT_HOST=luminostudio.ca
      - LETSENCRYPT_EMAIL=admin@doneztech.com
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./odoo:/opt/odoo  # <-- MANDATORY
      - odoo_local:/opt/odoo/.local
      - odoo_state:/opt/odoo/.db-initialized
      - /opt/ssl:/opt/ssl
      - ./config:/etc/odoo
      - ./custom_addons:/opt/odoo/custom_addons
    networks:
      - odoo-net
    command: >
      bash -c "
        sleep 10 ;
        exec python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf 
      "

  odoo-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-jobrunner
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./odoo:/opt/odoo  # <-- MANDATORY
      - odoo_local:/opt/odoo/.local
      - odoo_state:/opt/odoo/.db-initialized
      - /opt/ssl:/opt/ssl
      - ./config:/etc/odoo
      - ./custom_addons:/opt/odoo/custom_addons
    networks:
      - odoo-net
    command: >
      bash -c "
        sleep 15 ;
        exec python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf --workers=0 --load=web,queue_job
      "

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/etc/nginx/html
      - ./certbot/webroot:/var/www/certbot
      - /opt/ssl:/etc/letsencrypt
    networks:
      - odoo-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/webroot:/var/www/certbot
      - /opt/ssl:/etc/letsencrypt
    entrypoint: ""
    networks:
      - odoo-net
      - proxy     

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    networks:
      - odoo-net

volumes:
  db_data:
  odoo_local:
  odoo_state:
  certbot-webroot:

networks:
  odoo-net:
    driver: bridge
  proxy:           
    external: true
