version: "3.9"

services:
  db:
    image: postgres:14
    container_name: odoo-db
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - odoo-net

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-web
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST=mhs.doneztech.com
      - LETSENCRYPT_HOST=mhs.doneztech.com
      - LETSENCRYPT_EMAIL=admin@doneztech.com
      - MAX_CRON_THREADS=0
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./odoo:/opt/odoo
      - odoo_local:/opt/odoo/.local
      - odoo_state:/opt/odoo/.db-initialized
      - ./config:/etc/odoo
      - ./custom_addons:/opt/odoo/custom_addons
    networks:
      - odoo-net
    command: >
      bash -c "
        sleep 10 ;
        if [ ! -f /opt/odoo/.db-initialized ]; then
          echo 'Initializing db';
          python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf -d odoo -i base --without-demo=all --stop-after-init &&
          touch /opt/odoo/.db-initialized;
        fi;
        exec python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf 
      "
  odoo-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-jobrunner
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MAX_CRON_THREADS=1
    volumes:
      - ./odoo:/opt/odoo
      - odoo_local:/opt/odoo/.local
      - odoo_state:/opt/odoo/.db-initialized
      - ./config:/etc/odoo
      - ./custom_addons:/opt/odoo/custom_addons
    networks:
      - odoo-net
    command: >
      bash -c "
        sleep 15 ;
        exec python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf --workers=0 --load=web,queue_job
      "

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/etc/nginx/html
      - ./certbot/webroot:/var/www/certbot
      - /opt/ssl/certbot:/etc/letsencrypt
    depends_on:
      - odoo
    networks:
      - odoo-net
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/webroot:/var/www/certbot
      - /opt/ssl/certbot:/etc/letsencrypt
    entrypoint: ""
    networks:
      - odoo-net
      
  redis:
    image: redis:7
    restart: always

volumes:
  db_data:
  odoo_local:
  odoo_state:
  certbot-webroot:

networks:
  odoo-net:
    driver: bridge
