version: "3.9"

services:
  db:
    image: postgres:14
    container_name: odoo-db
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - odoo-net

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST=odoo.doneztech.com
      - LETSENCRYPT_HOST=odoo.doneztech.com
      - LETSENCRYPT_EMAIL=admin@doneztech.com
    ports:
      - "8069:8069"
    volumes:
      - ./odoo:/opt/odoo
      - odoo_local:/opt/odoo/.local
      - odoo_state:/opt/odoo/.db-initialized
      - ./config:/etc/odoo
      - ./custom_addons:/opt/odoo/custom_addons
    networks:
      - odoo-net
    command: >
      bash -c "
        sleep 10 ;
        if [ ! -f /opt/odoo/.db-initialized ]; then
          echo 'Initializing db';
          python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf -d odoo -i base --stop-after-init &&
          touch /opt/odoo/.db-initialized;
        fi;
        exec python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf 
      "
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - odoo
    networks:
      - odoo-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; while :; do 
        sleep 12h && wait $${!}; 
        certbot renew --webroot -w  /var/www/certbot &&
        nginx -s reload;
      ; done"
    networks:
      - odoo-net

volumes:
  db_data:
  odoo_local:
  odoo_state:

networks:
  odoo-net:
    driver: bridge
