version: "3.9"

services:
  db:
    image: postgres:14
    container_name: odoo-db
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./odoo:/opt/odoo
      - odoo_local:/opt/odoo/.local
      - odoo_state:/opt/odoo/.db-initialized
      - ./config:/etc/odoo
      - ./custom_addons:/opt/odoo/custom_addons
    command: >
      bash -c "
        sleep 10 &;
        if [ ! -f /opt/odoo/.db-initialized ]; then
          echo 'Initializing db';
          python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf -d odoo -i base --stop-after-init &&
          touch /opt/odoo/.db-initialized;
        fi;
        exec python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf
      "
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - odoo

volumes:
  db_data:
  odoo_local:
  odoo_state:
