version: "3.9"

services:
  odoo:
    image: ${ODOO_IMAGE}
    container_name: odoo-web
    restart: unless-stopped
    environment:
      - MAX_CRON_THREADS=0
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo_local:/opt/odoo/.local
      - odoo_state:/opt/odoo/.db-initialized
      - /opt/ssl:/opt/ssl
    networks:
      - odoo-net
    command: >
      bash -c "
        sleep 10 ;
        exec python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf 
      "

  odoo-runner:
    image: ${ODOO_IMAGE}
    container_name: odoo-jobrunner
    restart: unless-stopped
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
    volumes:
      - odoo_local:/opt/odoo/.local
      - odoo_state:/opt/odoo/.db-initialized
      - /opt/ssl:/opt/ssl
    networks:
      - odoo-net
    command: >
      bash -c "
        sleep 15 ;
        exec python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo.conf --workers=0 --load=web,queue_job
      "

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/etc/nginx/html
      - ./certbot/webroot:/var/www/certbot
      - /opt/ssl:/etc/letsencrypt
    networks:
      - odoo-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/webroot:/var/www/certbot
      - /opt/ssl:/etc/letsencrypt
    entrypoint: ""
    networks:
      - odoo-net

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    networks:
      - odoo-net

volumes:
  odoo_local:
  odoo_state:
  certbot-webroot:

networks:
  odoo-net:
    driver: bridge