name: Terraform Prod Deployment

on:
  workflow_dispatch:

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_CLOUD_TOKEN }}
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      odoo_ip: ${{ steps.extract.outputs.odoo_ip }}
      rds_endpoint: ${{ steps.rds_outputs.outputs.rds_endpoint }}
      rds_username: ${{ steps.rds_outputs.outputs.rds_username }}
      rds_password: ${{ steps.rds_outputs.outputs.rds_password }}
      rds_db_name: ${{ steps.rds_outputs.outputs.rds_db_name }}
      
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform init & Apply
      working-directory: infra/terraform/prod
      run: |
        terraform init
        terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-1

    - name: Print raw IP
      working-directory: infra/terraform/prod
      run: terraform output -raw odoo_server_ip

    - name: Terraform Output
      id: extract
      working-directory: infra/terraform/prod
      run: |
        SERVER_IP=$(terraform output -raw odoo_server_ip | tr -d '\r\n%' | sed 's/::.*//')
        echo "odoo_ip=${SERVER_IP}" >> $GITHUB_OUTPUT
    
    - name: Get RDS Endpoint
      working-directory: infra/terraform/prod
      run: terraform output -raw rds_endpoint
      
    - name: Export RDS Outputs
      id: rds_outputs
      working-directory: infra/terraform/prod
      run: |
        echo "rds_endpoint=$(terraform output -raw rds_endpoint | cut -d':' -f1)" >> $GITHUB_ENV
        echo "rds_username=$(terraform output -raw rds_username)" >> $GITHUB_ENV
        echo "rds_password=$(terraform output -raw rds_password)" >> $GITHUB_ENV
        echo "rds_db_name=$(terraform output -raw rds_db_name)" >> $GITHUB_ENV